package com.example.test_kotlin

import androidx.lifecycle.MutableLiveData
import androidx.lifecycle.ViewModel

class MainViewModel : ViewModel() {
    private var liveData: MutableLiveData<ArrayList<LayoutHolder>> = MutableLiveData()
    private var dataList = ArrayList<LayoutHolder>()

    fun add(): MutableLiveData<ArrayList<LayoutHolder>> {
        return liveData
    }

    fun setDataUsingViewModel() {
        dataList.add(
            LayoutHolder(
                LayoutHolderAdapter.THE_FIRST_VIEW,
                R.drawable.businessman1,
                "Text-1",
                "Text-1"
            )
        )
        dataList.add(
            LayoutHolder(
                LayoutHolderAdapter.THE_SECOND_VIEW,
                R.drawable.bussinessman2,
                "Text-1",
                "Text-2"
            )
        )
        dataList.add(
            LayoutHolder(
                LayoutHolderAdapter.THE_THIRD_VIEW,
                R.drawable.businessman1,
                "Text-1",
                "Text-2"
            )
        )
        dataList.add(
            LayoutHolder(
                LayoutHolderAdapter.THE_FIRST_VIEW,
                R.drawable.bussinessman2,
                "Text-1",
                "Text-2"
            )
        )
        dataList.add(
            LayoutHolder(
                LayoutHolderAdapter.THE_SECOND_VIEW,
                R.drawable.bussinessman2,
                "Text-1",
                "Text-2"
            )
        )
        dataList.add(
            LayoutHolder(
                LayoutHolderAdapter.THE_THIRD_VIEW,
                R.drawable.bussinessman2,
                "Text-1",
                "Text-2"
            )
        )
        dataList.add(
            LayoutHolder(
                LayoutHolderAdapter.THE_FIRST_VIEW,
                R.drawable.man,
                "Text-1",
                "Text-2"
            )
        )
        dataList.add(
            LayoutHolder(
                LayoutHolderAdapter.THE_SECOND_VIEW,
                R.drawable.bussinessman2,
                "Text-1",
                "Text-2"
            )
        )
        dataList.add(
            LayoutHolder(
                LayoutHolderAdapter.THE_THIRD_VIEW,
                R.drawable.man,
                "Text-1",
                "Text-2"
            )
        )
        dataList.add(
            LayoutHolder(
                LayoutHolderAdapter.THE_FIRST_VIEW,
                R.drawable.person,
                "Text-1",
                "Text-2"
            )
        )
        dataList.add(
            LayoutHolder(
                LayoutHolderAdapter.THE_SECOND_VIEW,
                R.drawable.person,
                "Text-1",
                "Text-2"
            )
        )
        dataList.add(
            LayoutHolder(
                LayoutHolderAdapter.THE_THIRD_VIEW,
                R.drawable.person,
                "Text-1",
                "Text-2"
            )
        )
        dataList.add(
            LayoutHolder(
                LayoutHolderAdapter.THE_FIRST_VIEW,
                R.drawable.woman,
                "Text-1",
                "Text-2"
            )
        )
        dataList.add(
            LayoutHolder(
                LayoutHolderAdapter.THE_SECOND_VIEW,
                R.drawable.woman,
                "Text-1",
                "Text-2"
            )
        )
        dataList.add(
            LayoutHolder(
                LayoutHolderAdapter.THE_THIRD_VIEW,
                R.drawable.woman,
                "Text-1",
                "Text-2"
            )
        )
        dataList.add(
            LayoutHolder(
                LayoutHolderAdapter.THE_FIRST_VIEW,
                R.drawable.man1,
                "Text-1",
                "Text-2"
            )
        )
        dataList.add(
            LayoutHolder(
                LayoutHolderAdapter.THE_SECOND_VIEW,
                R.drawable.man1,
                "Text-1",
                "Text-2"
            )
        )
        dataList.add(
            LayoutHolder(
                LayoutHolderAdapter.THE_THIRD_VIEW,
                R.drawable.man1,
                "Text-1",
                "Text-2"
            )
        )
        liveData.value = dataList
    }
}